<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path__cx-svg-icon-tone1</name>
   <tag></tag>
   <elementGuidId>76961efb-bc37-41c7-94aa-1505fcfab53e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path.cx-svg-icon-tone1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cx-svg-icon-tone1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M100,14.29,64.28,50,100,85.7,85.7,100,50,64.28,14.3,100,0,85.7,35.72,50,0,14.29,14.3,0,50,35.71,85.7,0Z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(-0.02 -0.01)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;hasTranslate-gN08H-U-Gw js-focus-visible&quot;]/div[@class=&quot;cx-widget cx-window-manager cx-theme-light&quot;]/div[@class=&quot;cx-dock cx-first cx-dock-view cx-docked-Engage cx-desktop&quot;]/div[@class=&quot;cx-widget cx-common-container cx-close cx-engage-toast cx-toast cx-toaster cx-theme-light cx-desktop&quot;]/div[@class=&quot;cx-button-group cx-buttons-window-control&quot;]/button[@class=&quot;cx-icon cx-button-close&quot;]/svg[1]/path[@class=&quot;cx-svg-icon-tone1&quot;]</value>
   </webElementProperties>
</WebElementEntity>
